CREATE TABLE PERSON(
	ID SERIAL PRIMARY KEY,
	FIRST_NAME VARCHAR(20) NOT NULL, -- НЕ МОЖЕ БУТИ ПРОПУСКУ
	LAST_NAME VARCHAR(20) UNIQUE, -- МАЮТЬ БУТИ ІНІКАЛНИМИ(БЕЗ ПОВТОРІВ)
	AGE INT CHECK(AGE > 0), -- НЕ МОЖЕ БУТИ ВІД'ЄМНИМ
	CITY VARCHAR(30) DEFAULT 'ЗАПОРІЖЖЯ',  -- ЗА ЗАМОВЧУВАННЯМ, ВВАЖАЄМО ЩО ЗАПОРІЖЖЯ
	BIRTH_DATE DATE NOT NULL CHECK(BIRTH_DATE > '1925-01-01')
)


-- ЗАПОВНЕННЯ
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, AGE, CITY, BIRTH_DATE) VALUES ('Іван', 'Шевченко', 25, 'Київ', '1999-03-15');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, AGE, CITY, BIRTH_DATE) VALUES ('Марія', 'Ковальчук', 30, 'Львів', '1994-07-22');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, AGE, CITY, BIRTH_DATE) VALUES ('Андрій', 'Петренко', 28, DEFAULT, '1996-01-10');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, AGE, CITY, BIRTH_DATE) VALUES ('Оксана', 'Мельник', 22, 'Одеса', '2002-11-05');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, AGE, CITY, BIRTH_DATE) VALUES ('Сергій', 'Захарченко', 35, 'Харків', '1989-06-17');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, AGE, CITY, BIRTH_DATE) VALUES ('Олена', 'Гончаренко', 26, DEFAULT, '1998-04-08');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, AGE, CITY, BIRTH_DATE) VALUES ('Дмитро', 'Романюк', 31, 'Тернопіль', '1993-12-01');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, AGE, CITY, BIRTH_DATE) VALUES ('Наталія', 'Кузьменко', 27, 'Рівне', '1997-05-19');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, AGE, CITY, BIRTH_DATE) VALUES ('Віктор', 'Семенов', 29, DEFAULT, '1995-09-30');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, AGE, CITY, BIRTH_DATE) VALUES ('Ірина', 'Ткаченко', 24, 'Черкаси', '2000-02-14');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, AGE, CITY, BIRTH_DATE) VALUES ('Руслан', 'Гриценко', 32, 'Івано-Франківськ', '1992-10-10');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, AGE, CITY, BIRTH_DATE) VALUES ('Юлія', 'Данилюк', 33, DEFAULT, '1991-08-25');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, AGE, CITY, BIRTH_DATE) VALUES ('Тарас', 'Кравченко', 23, 'Хмельницький', '2001-06-03');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, AGE, CITY, BIRTH_DATE) VALUES ('Світлана', 'Литвин', 34, 'Полтава', '1990-04-27');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, AGE, CITY, BIRTH_DATE) VALUES ('Олег', 'Яценко', 21, DEFAULT, '2003-12-12');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, AGE, CITY, BIRTH_DATE) VALUES ('Катерина', 'Чорна', 36, 'Чернівці', '1988-03-03');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, AGE, CITY, BIRTH_DATE) VALUES ('Артур', 'Бондар', 20, 'Житомир', '2004-09-21');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, AGE, CITY, BIRTH_DATE) VALUES ('Лілія', 'Мазур', 38, DEFAULT, '1986-01-01');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, AGE, CITY, BIRTH_DATE) VALUES ('Євген', 'Савчук', 27, 'Ужгород', '1997-07-07');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, AGE, CITY, BIRTH_DATE) VALUES ('Аліна', 'Зінченко', 22, 'Дніпро', '2002-10-20');

-- ПОГАНІ ДАНІ
--INSERT INTO PERSON (FIRST_NAME, LAST_NAME, AGE, CITY, BIRTH_DATE) VALUES ('А', 'Б', 22, 'Дніпро', '1802-10-20');
INSERT INTO PERSON (FIRST_NAME, BIRTH_DATE) VALUES ('А', '2002-10-20');

SELECT *
FROM PERSON

